project:
  type: website
  output-dir: docs

website:
  title: "Raptor"
  navbar:
    background: "#0a0e1a"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
  page-footer:
    center: "Â© 2026 Raptor Liquidity. All rights reserved."

format:
  html:
    theme: darkly
    css: styles.css
    toc: false
